repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-added-large-files # default is 500kB
        args: [--maxkb=10240]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.9.0]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
        types: [file,python]
#  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
#    rev: v1.0.3
#    hooks:
#      - id: gitlab-ci-linter
#        args:
#          - --filename=.ci/gitlab-ci.yml
